# Learn PyTorch

In [1]:
pip install torch torchvision torchaudio

INFO: pip is looking at multiple versions of torchaudio to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 3.1 MB/s eta 0:00:000:00:010:00:01:01
Note: you may need to restart the kernel to use updated packages.


## Stage 1 : 🔥 Stage 1: PyTorch Tensors (Your First Building Block)

In [3]:
import torch

In [4]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [6]:
torch.rand(2,3)

tensor([[0.4049, 0.2896, 0.8259],
        [0.6740, 0.8465, 0.7263]])

In [7]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
torch.linspace(0,5,steps=5)

tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000])

In [11]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
x+y

tensor([5., 7., 9.])

In [14]:
# matrix multiplication
x@y

tensor(32.)

In [17]:
x.reshape(3,1)

tensor([[1.],
        [2.],
        [3.]])

In [18]:
x.view(3,1)

tensor([[1.],
        [2.],
        [3.]])

In [22]:
# Add a tensor of ones on 3 by 3 tensor
tensor_3_by_3 = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
ones = torch.ones(3,3)
addition= tensor_3_by_3 + ones
addition

tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]])

In [26]:
# Multiply by 2
multiplication_by_2 = addition *2
multiplication_by_2

tensor([[ 4.,  6.,  8.],
        [10., 12., 14.],
        [16., 18., 20.]])

In [28]:
reshape_1_9 = multiplication_by_2.reshape(1,9)
reshape_1_9

tensor([[ 4.,  6.,  8., 10., 12., 14., 16., 18., 20.]])

## Stage 2 : Autograde Basics

In [33]:
x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 3*x+5
y

tensor(15., grad_fn=<AddBackward0>)

In [34]:
y.backward()

In [37]:
x.grad

tensor(7.)

In [38]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = (x ** 2).sum()   # y = x1^2 + x2^2 + x3^2
y.backward()

print(x.grad)  # tensor([2., 4., 6.])

tensor([2., 4., 6.])


In [40]:
# Stopping gradient
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2

with torch.no_grad():
    z = y * 2   # no gradient tracking here

print(z.requires_grad)  # False

False


In [41]:
# Clear old gradient
w = torch.tensor(2.0, requires_grad=True)

for i in range(3):
    y = w * 3
    y.backward()
    print(w.grad)  # gradients accumulate!

    w.grad.zero_()  # reset gradients

tensor(3.)
tensor(3.)
tensor(3.)


In [43]:
x = torch.tensor(4.0, requires_grad=True)
y = 3*x**3 + 2*x**2 + 7
y.backward()
print(x.grad)

tensor(160.)


## 🔥 Stage 3: Neural Networks with nn.Module

In [47]:
import torch
import torch.nn as nn

# Define model
class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)  # input size=1, output size=1

    def forward(self, x):
        return self.linear(x)

# Create model
model = LinearModel()
print(model)

LinearModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


In [48]:
x = torch.tensor([[2.0]])   # input (batch_size=1, features=1)
y_pred = model(x)           # forward pass
print(y_pred)

tensor([[0.0641]], grad_fn=<AddmmBackward0>)


In [49]:
# True data
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
Y = torch.tensor([[3.0], [5.0], [7.0], [9.0]])

# Model
model = LinearModel()

# Loss function (Mean Squared Error)
criterion = nn.MSELoss()

# Optimizer (Stochastic Gradient Descent)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [50]:
for epoch in range(500):
    # Forward pass
    Y_pred = model(X)
    loss = criterion(Y_pred, Y)

    # Backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch+1) % 50 == 0:
        print(f'Epoch {epoch+1}, Loss: {loss.item():.4f}')

Epoch 50, Loss: 0.0163
Epoch 100, Loss: 0.0121
Epoch 150, Loss: 0.0089
Epoch 200, Loss: 0.0066
Epoch 250, Loss: 0.0049
Epoch 300, Loss: 0.0036
Epoch 350, Loss: 0.0027
Epoch 400, Loss: 0.0020
Epoch 450, Loss: 0.0015
Epoch 500, Loss: 0.0011


In [51]:
x_test = torch.tensor([[5.0]])
y_test = model(x_test)
print("Prediction for x=5:", y_test.item())

Prediction for x=5: 11.056589126586914


## 🔥 Stage 4: Loss Functions & Optimizers in PyTorch